# -*- coding: utf-8 -*-
"""Breast_Cancer_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IZOrCGVBpdhpWTtyjtoV6NMCCo895NnB
"""

import pandas as pd
import numpy as np

"""Carregamento dos dados que estão no GitHub"""

urlpredictor = 'https://raw.githubusercontent.com/JrSousaJ/Breast_Cancer/master/input.csv'
urlclass = 'https://raw.githubusercontent.com/JrSousaJ/Breast_Cancer/master/output.csv'

predictor = pd.read_csv(urlpredictor)
bcclass = pd.read_csv(urlclass)

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout

classifier = Sequential()
classifier.add(Dense(units = 8, activation="relu", 
                  kernel_initializer="normal", input_dim=30))
classifier.add(Dropout(0.2))
classifier.add(Dense(units = 8, activation="relu", 
                  kernel_initializer="normal"))
classifier.add(Dropout(0.2))
classifier.add(Dense(units = 1, activation="sigmoid"))
#ooptimizer = keras.optimizers.Adam(lr=0.005,decay=0.0001,clipvalue=0.5)
classifier.compile(optimizer="adam", loss="binary_crossentropy", 
            metrics=["binary_accuracy"])

classifier.fit(predictor, bcclass, batch_size = 10, epochs = 200)

newregister = np.array([[15.80, 8.34, 118, 900, 0.10, 0.26, 0.08, 0.134, 0.178,
                  0.20, 0.05, 1098, 0.87, 4500, 145.2, 0.005, 0.04, 0.05, 0.015,
                  0.03, 0.007, 23.15, 16.64, 178.5, 2018, 0.14, 0.185,
                  0.84, 158, 0.363]])

predictionreg = classifier.predict(newregister)
print("Tumor Maligno" if(predictionreg > 0.5) else "Tumor Benigno")